version: 2

defaults: &defaults
  working_directory: ~/jimp
  docker:
    - image: circleci/node:10-browsers

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Build Packages
          command: yarn build
      - save_cache:
          key: jimp-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - ~/.cache/yarn
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/jimp
      - run:
          name: Lint
          command: yarn lint

  test-types:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/jimp
      - run:
          name: Test Types
          command: yarn tsTest:custom && yarn tsTest:main

  build-node8:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/jimp
      - run:
          name: Build Packages
          command: yarn build
      - run:
          name: Test
          command: yarn test --ci
      - run:
          name: Test Browser
          command: yarn test:browser --ci
      - persist_to_workspace:
          root: .
          paths:
            - .

  build-node10:
    working_directory: ~/jimp-10
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --network-timeout 100000
      - run:
          name: Build Packages
          command: yarn build
      - run:
          name: Test
          command: yarn test --ci

  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/jimp
      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Release the Project
          command: yarn release
workflows:
  version: 2
  build_and_test:
    jobs:
      - install

      - lint:
          requires:
            - install

      - test-types:
          requires:
            - install

      - build-node8:
          requires:
            - lint
            - test-types

      - build-node10:
          requires:
            - lint
            - test-types

      - release:
          requires:
            - build-node8
